/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Billboard.glb -o src/components/Billboard.jsx -r public 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Billboard(props) {
  const { nodes, materials } = useGLTF("/models/Billboard.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.c.geometry} material={materials.lambert3SG} />
      <mesh geometry={nodes.b.geometry} material={materials.lambert3SG} />
    </group>
  );
}

useGLTF.preload("/models/Billboard.glb");
