/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Building.glb -o src/components/building.jsx -r public 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Building(props) {
  const { nodes, materials } = useGLTF("/models/Building.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.building_F.geometry}
        material={materials.citybits_texture}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/Building.glb");
