/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: BenK (https://sketchfab.com/BenK656)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-sims-plumbob-8dadd87ba9e049c596765857fff2f527
Title: The Sims: Plumbob
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function PlayerIndicator(props) {
  const { nodes, materials } = useGLTF("/models/Indicator/indicator.gltf");
  const group = useRef();
  useFrame(({ clock }) => {
    const t = clock.getElapsedTime();
    group.current.position.y = Math.sin(t) * 0.05 + 1.8;
    group.current.rotation.y = Math.sin(t) * 2;
  });
  return (
    <group {...props} ref={group} dispose={null} scale={0.07} position-y={1.8}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial.geometry}
          material={materials.rampShader1}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/Indicator/indicator.gltf");
